In [76]:
import numpy as np

In [104]:
def max_ae(a, b):
    """"""
    return np.max(np.abs(a - b))

def mse(a, b):
    """"""
    return np.mean(np.abs(a - b)**2)

basedir = '/Users/nick11roberts/github.com/Sala-Group/WS-Struct-Pred'


In [105]:
obj = 'M3'
#obj = 'ex32'

pn = 'pos'
dir_hat = f'T_{pn}_hat'
dir_td = f'T_{pn}_td'

a = np.load(f'{basedir}/code/{dir_hat}/{obj}.npy')
b = np.load(f'{basedir}/code/{dir_td}/{obj}.npy')


#np.linalg.eig()

print('max_ae\t', max_ae(a, b))
print('mse\t', mse(a, b))


max_ae	 0.3220881407543086
mse	 0.0022394177647732222


In [106]:
vals, vecs = np.linalg.eig(a)
np.sort(np.real(vals))

array([[-2.49514072e+00, -4.03593570e-01, -2.11704533e-15,
         5.39589300e-19,  5.39589300e-19,  1.19043844e-17],
       [-5.82058841e+00, -4.03643416e-16, -9.66418935e-17,
         2.07881425e-16,  2.23200332e-15,  1.93071041e-01],
       [-1.27990085e-16, -1.27990085e-16,  1.08458960e-16,
         6.74055928e-16,  9.68585625e-02,  3.12121728e+00],
       [-1.84341662e+00, -2.15665743e-15, -9.48707309e-17,
         3.04558335e-16,  2.40400599e-14,  1.90392923e+01],
       [-5.65198538e+00, -2.14928948e-15, -3.30080253e-16,
         1.04488439e-16,  3.32835884e-16,  1.32437798e+00],
       [ 1.03722055e-15,  4.43703733e-15,  6.29950969e-15,
         1.00040784e-14,  5.14472846e+00,  7.96124617e+01]])

In [107]:
vals, vecs = np.linalg.eig(b)
np.sort(np.real(vals))

array([[-2.56737256e+00, -4.12910956e-01, -4.96995550e-17,
        -2.90567108e-18, -2.90567108e-18,  1.73082526e-17],
       [-5.89019462e+00, -6.64700055e-17,  3.25958155e-18,
         3.25958155e-18,  7.05698132e-17,  1.79976440e-01],
       [-2.77813603e-17,  5.01360665e-18,  7.38404228e-18,
         7.38404228e-18,  1.35428144e-01,  3.12837950e+00],
       [-1.77385588e+00, -8.61233644e-16, -8.96676949e-17,
         3.55077681e-17,  5.12287097e-16,  1.93071906e+01],
       [-5.51201316e+00, -7.95965943e-17, -7.95965943e-17,
        -2.25721546e-18,  1.94375123e-16,  1.52312675e+00],
       [ 9.22926572e-17,  1.16583391e-16,  4.56244925e-16,
         4.56244925e-16,  5.15938904e+00,  7.96832936e+01]])

In [81]:
def lowrank(x, k):
    u, s, vh = np.linalg.svd(x)
    s_abs = np.abs(s)
    inds = np.argsort(s_abs)[::-1][:k]
    rec = np.zeros_like(x)
    for i in inds:
        rec += s[i] * np.outer(u.T[i], vh[i])
    return rec

In [82]:
a_rec = lowrank(a, k=2)
vals, vecs = np.linalg.eig(a_rec)
np.sort(np.real(vals))

array([-4.85132302e-17, -4.17386606e-17,  5.25805207e-17,  1.43292661e-16,
        1.08387962e+00,  5.70668119e+00])

In [83]:
a_inv = np.linalg.pinv(a)
vals, vecs = np.linalg.eig(a_inv)
np.sort(np.real(vals))

array([5.66244972e-18, 1.39335120e-17, 1.39335120e-17, 5.85177886e-17,
       1.68450000e-01, 8.45723189e-01])

In [84]:
a_rec_inv = np.linalg.pinv(a_rec)
vals, vecs = np.linalg.eig(a_rec_inv)
np.sort(np.real(vals))

array([-3.45512467e-17, -7.12771329e-18,  1.47878152e-17,  6.94826652e-17,
        1.68450000e-01,  8.45723189e-01])

In [85]:
b_inv = np.linalg.pinv(b)
vals, vecs = np.linalg.eig(b_inv)
np.sort(np.real(vals))

array([-1.92433545e-17, -8.83821729e-18,  8.57067875e-18,  8.57067875e-18,
        1.56106792e-01,  9.16085614e-01])

In [86]:
max_mae(a_rec_inv, b_inv)

0.1309167165859809